name: Tostadas CI (Conda)

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
        bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge
        export PATH="$HOME/mambaforge/bin:$PATH"
        conda update conda
        mamba env create -f environment.yml
        mamba clean -a -y
        echo "source activate tostadas" > ~/.bashrc && source activate tostadas
        conda install samtools=1.14
        mamba install -c bioconda nextflow
        conda install pandas
    
    - name: Install Pytest
      run: pip install pytest
      
    - name: Run Tests
      run: pytest -p no:warnings tests/test_main.py
