name: Tostadas CI

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
        bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge
        export PATH="$HOME/mambaforge/bin:$PATH"
        mamba env create -f environment.yml
        source activate tostadas
        mamba install -c bioconda nextflow
    
    - name: Install Pytest
      run: pip install pytest
    
    - name: Initialize Submodule
      run: |
        git submodule init
        git submodule update --remote

    - name: Run Tests
      run: pytest -p no:warnings tests/test_main.py
