name: Tostadas CI (Conda)

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Copy Test File
      run: cp tests/test_main.py .github/workflows/

    - name: Change Directories
      run: cd .github/workflows/

    - name: Build Docker Image
      run: docker build -t CI-Tostadas .

    - name: Run Tests
      run: docker run --rm -v CI-Tostadas pytest -p no:warnings test_main.py