name: Tostadas CI (Conda)

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Mambaforge
      run: |
        curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
        bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge
        export PATH="$HOME/mambaforge/bin:$PATH"

    - name: Verify Mamba installation
      run: $HOME/mambaforge/bin/mamba --version
    
    - name: Initialize Conda shell
      run: |
        echo ". $HOME/mambaforge/etc/profile.d/conda.sh" >> $HOME/.bashrc
        echo "conda activate tostadas" >> $HOME/.bashrc

    - name: Create and Activate Environment
      run: |
        source $HOME/.bashrc
        conda init bash
        conda activate tostadas

    - name: Install Dependencies
      run: |
        $HOME/mambaforge/bin/mamba install -c bioconda nextflow
        conda install pandas
        conda install pytest
        conda install glob2
        pip install pytest
      
    - name: Run Tests
      run: |
        pytest -p no:warnings tests/test_main.py