name: Tostadas CI (Conda)

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Copy Test File
      run: cp tests/test_main.py .github/workflows/

    - name: Build Docker Image
      run: cd .github/workflows/ && docker build -t ci_tostadas .

    - name: Run Tests
      run: docker run -v ./:./ ci_tostadas