name: Tostadas CI (Conda)

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    
    - name: Install Miniconda
      run: |
        curl -LO https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"

    - name: Verify Conda installation
      run: conda --version

    - name: Create and Activate Environment
      run: |
        conda env create -n ci_tostadas -f environment.yml
        conda activate ci_tostadas

    - name: Install Nextflow
      run: |
        conda install -c bioconda nextflow

    - name: Run Tests
      run: |
        pytest -p no:warnings tests/test_main.py