name: Tostadas CI

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
        bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge
        export PATH="$HOME/mambaforge/bin:$PATH"
        mamba env create -f environment.yml
        source activate tostadas
        mamba install -c bioconda nextflow
    
    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: pytest